//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelos
    {
        public Vuelos()
        {
            this.Boletos = new HashSet<Boletos>();
        }
    
        public string AerolineaID { get; set; }
        public int ConexionID { get; set; }
        public int numeroVuelo { get; set; }
        public System.DateTime fecha { get; set; }
        public int asientosDisponibles { get; set; }
        public int capacidad { get; set; }
        public string fechaParaMostrar { get { return this.fecha.Day + "/" + this.fecha.Month + "/" + this.fecha.Year; } }
        public string infoVuelo { get {return "Fecha: "+ this.fecha.Day +"/"+this.fecha.Month+"/"+this.fecha.Year+" - Aerolinea: "+ this.AerolineaID+ " - Numero de vuelo: "+ this.numeroVuelo +" - Numero de conexion: "+ this.ConexionID +" - Ciudad origen: "+this.Conexiones.CiudadOrigen+ " - Ciudad destino: "+this.Conexiones.CiudadDestino ; } }
    
        public virtual ICollection<Boletos> Boletos { get; set; }
        public virtual Conexiones Conexiones { get; set; }
    }
}
