//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionamientoMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstacionamientoMVCEntities : DbContext
    {
        public EstacionamientoMVCEntities()
            : base("name=EstacionamientoMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<parcela> parcela { get; set; }
        public DbSet<registros> registros { get; set; }
        public DbSet<tipoDeVehiculo> tipoDeVehiculo { get; set; }
        public DbSet<vehiculo> vehiculo { get; set; }
    }
}
