//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionamientoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoDeVehiculo
    {
        public tipoDeVehiculo()
        {
            this.vehiculo = new HashSet<vehiculo>();
        }
    
        public int idTipo { get; set; }
        public string nombre { get; set; }
        public double tarifa { get; set; }
    
        public virtual ICollection<vehiculo> vehiculo { get; set; }
    }
}
