//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionamientoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        public vehiculo()
        {
            this.registros = new HashSet<registros>();
        }
    
        public string patente { get; set; }
        public int idTipo { get; set; }
        public string marca { get; set; }
    
        public virtual ICollection<registros> registros { get; set; }
        public virtual tipoDeVehiculo tipoDeVehiculo { get; set; }
    }
}
